stages:
- test
- pre-build
- build
- deployment

variables:
  VAR_KUBE_CONTEXT: $ENV

test:
  stage: test
  image: ruby:2.4.2
  script:
  - make dep test

build-image:
  stage: build
  image: registry.bukalapak.io/sre/gudang/docker:1.0.0
  tags:
  - build-image
  only:
  - triggers
  script:
  - export VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - make build push

.deploy-template: &deploy-template
  stage: deployment
  image: registry.bukalapak.io/sre/gudang/deployment:2.2.0
  tags:
  - bare-metal
  only:
  - triggers
  script:
  - export VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
  - kubectl config use-context $VAR_KUBE_CONTEXT
  - make deploy

deploy:
  <<: *deploy-template

deploy-service:
  <<: *deploy-template
  allow_failure: true
  when: manual
  variables:
    FILE: service
